### ISSUE TITLE
I didn't see the secrets

### ISSUE THREAD

**Issue by KevinNitroG** [longtoZ/gamestore#1]
https://github.com/longtoZ/gamestore/blob/70c7492d7d87b7b59df34a04a44c46b4afeb44f6/.env
🐧

**Comment by longtoZ** [comment]
> https://github.com/longtoZ/gamestore/blob/70c7492d7d87b7b59df34a04a44c46b4afeb44f6/.env 🐧

Web lỏ lười giấu ((:
